# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pagamentos.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_dados = QtWidgets.QFrame(self.centralwidget)
        self.frame_dados.setGeometry(QtCore.QRect(10, 10, 281, 171))
        self.frame_dados.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dados.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dados.setObjectName("frame_dados")
        self.label = QtWidgets.QLabel(self.frame_dados)
        self.label.setGeometry(QtCore.QRect(10, 25, 36, 17))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.frame_dados)
        self.comboBox.setGeometry(QtCore.QRect(60, 71, 150, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame_dados)
        self.label_2.setGeometry(QtCore.QRect(10, 71, 44, 17))
        self.label_2.setObjectName("label_2")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_dados)
        self.dateEdit.setGeometry(QtCore.QRect(60, 117, 107, 26))
        self.dateEdit.setObjectName("dateEdit")
        self.label_3 = QtWidgets.QLabel(self.frame_dados)
        self.label_3.setGeometry(QtCore.QRect(10, 117, 33, 17))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_dados)
        self.lineEdit.setGeometry(QtCore.QRect(60, 25, 142, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 250, 631, 221))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Valor"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Cartão de Debito"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Cartão de Credito"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Dinheiro"))
        self.label_2.setText(_translate("MainWindow", "Forma"))
        self.label_3.setText(_translate("MainWindow", "Data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Data"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Valor"))
